### PR TITLE
Added default_case option for Response plug

### PR DESCRIPTION
**Pull request by madshargreave**

### CODE REVIEW

**Comment by anthonator** [comment]
Thanks for putting this together! Sorry for not getting back to this sooner. Had a short week last week.

What if someone passes in an unsupported case? Should the default case be used?

**Comment by tf** [comment]
I also think falling back to the default in unsupported cases would make sense.

**Comment by anthonator** [comment]
@madshargreave could you implement a fallback to `:default_case` in the event an unsupported case is provided?

**Comment by anthonator** [comment]
Closing due to inactivity.

**Pull request closed without merging**
